### ISSUE TITLE
Failing to load all procedures in plugin, only `spatial.osm` are loaded

### ISSUE THREAD

**Issue by theweaklink** [neo4j-contrib/spatial-algorithms#7]
Hello,

I'm a bit puzzled trying to load this plugin in Neo4j, I must be missing something simple. After downloading into neo4j plugin directory and setting the right group ownership, the procedures seem to load only partially: I only see the `spatial.osm` procedures, not the `spatial.algo` ones.

![Screenshot from 2021-06-21 09-12-39](https://user-images.githubusercontent.com/21156424/122722131-ab2e2e80-d271-11eb-84be-2813f2b349d4.png)

I tried to set the neo4j.conf to the following:
```
dbms.security.procedures.allowlist=apoc.*, spatial.*
dbms_security_procedures_unrestricted=apoc.*, spatial.*
```

but it did not change anything (side note: all `apoc` functions are there, no problem on that end)

If anyone has a clue, it would be much appreciated.
thank you!

(btw, very nice post, thank you! :+1:   : https://neo4j.com/blog/building-spatial-search-algorithms-neo4j/)

**Comment by SuperSuperDev** [comment]
@theweaklink They are listed under functions. Try:
```.cy

// List functions
CALL dbms.functions()
```

**Comment by theweaklink** [comment]
Thanks a lot!
(I kept focusing on procedures, oops... :roll_eyes:  )
